# Generated by Django 5.0.1 on 2024-02-05 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
