# Generated by Django 5.0.1 on 2024-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listnode',
            name='last_action',
            field=models.CharField(blank=True, default='', max_length=258, null=True),
        ),
    ]
