# Generated by Django 5.0.1 on 2024-05-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_group_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
