# Generated by Django 5.0.1 on 2024-03-08 08:22

import autoslug.fields
import django.db.models.deletion
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_today', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=index.models.Project.custom_populate_from, unique_with=['profile__user__username'])),
                ('title', models.CharField(default='⚡ New Project!', max_length=64)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='projects_allowed_in', to='profiles.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ListNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('content', models.TextField(default='Your note here.')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.project')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.project'),
        ),
    ]
