# Generated by Django 5.0.1 on 2024-03-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_listnode_user_alter_group_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='listnode',
            old_name='user',
            new_name='profile',
        ),
    ]
