# Generated by Django 5.0.1 on 2024-03-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_group_title_alter_listnode_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(default='New Group', max_length=32),
        ),
    ]
